// Non-AI Unpredictability Engine (pure functions)
// Provides weighted random events for habits plus time-based triggers.

const config = {
  baseWeights: {
    chaos: 2,
    reward: 4,
    shadow: 2,
    pattern: 2,
    nothing: 8,
  },
  streakBoost: { threshold: 7, chaos: 2, reward: 3 },
  missBoost: { threshold: 3, shadow: 3, chaos: 2 },
  lowDaysBoost: { threshold: 3, reward: 2 },
};

let uidCounter = 0;
export const uid = () => {
  uidCounter += 1;
  return `e_${Date.now()}_${uidCounter}`;
};

export const clamp = (num, min, max) => Math.min(Math.max(num, min), max);

export const weightedPick = (pairs) => {
  const total = pairs.reduce((sum, p) => sum + (p.weight || 0), 0);
  if (total <= 0) return null;
  const roll = Math.random() * total;
  let acc = 0;
  for (const p of pairs) {
    acc += p.weight || 0;
    if (roll <= acc) return p.item;
  }
  return null;
};

const microRewardTable = [
  { item: { type: "xp", amount: 1, label: "+1 XP" }, weight: 6 },
  { item: { type: "xp", amount: 3, label: "+3 XP" }, weight: 4 },
  { item: { type: "xp", amount: 5, label: "+5 XP" }, weight: 2 },
  { item: { type: "badge", id: "lucky-spark", label: "Lucky Spark" }, weight: 1 },
];

export const weightedReward = () => weightedPick(microRewardTable);

const chaosTemplates = {
  easy: () => ({
    id: uid(),
    title: "Chaos: Tiny Disruption",
    description: "Do a 5-minute reset to regain focus.",
    difficulty: "Easy",
    xp: 5,
    credits: 0,
    autoGenerated: true,
    createdAt: new Date().toISOString(),
  }),
  medium: () => ({
    id: uid(),
    title: "Chaos: Rapid Shuffle",
    description: "Swap your next task with a quick win.",
    difficulty: "Normal",
    xp: 10,
    credits: 5,
    autoGenerated: true,
    createdAt: new Date().toISOString(),
  }),
  insane: () => ({
    id: uid(),
    title: "Chaos: Boss Room",
    description: "Take on the hardest subtask for 10 minutes.",
    difficulty: "Hard",
    xp: 20,
    credits: 10,
    autoGenerated: true,
    createdAt: new Date().toISOString(),
  }),
};

export const makeChaosQuest = (difficulty = "easy") => {
  const key = difficulty === "insane" ? "insane" : difficulty === "medium" ? "medium" : "easy";
  return chaosTemplates[key]();
};

const patternMessages = [
  "Invert your routine: start with a stretch.",
  "Micro-break: 90 seconds of breathing.",
  "Shuffle order: do the smallest item first.",
  "Stand up and change posture for 3 minutes.",
];

const makePatternBreaker = () => ({
  id: uid(),
  type: "pattern_break",
  title: "Pattern Breaker",
  message: patternMessages[Math.floor(Math.random() * patternMessages.length)],
});

const makeShadowWarning = (habit) => {
  const base = habit?.notes || habit?.name || habit?.tags?.[0] || "habit";
  const excerpt = base.length > 80 ? `${base.slice(0, 77)}...` : base;
  return {
    id: uid(),
    type: "shadow_warning",
    message: `Shadow detected: ${excerpt}`,
  };
};

const buildWeights = (habit, context = {}) => {
  const { baseWeights, streakBoost, missBoost, lowDaysBoost } = config;
  const weights = { ...baseWeights };

  if ((context.streak || 0) >= streakBoost.threshold) {
    weights.chaos += streakBoost.chaos;
    weights.reward += streakBoost.reward;
  }

  if ((context.missedCountLast7 || 0) >= missBoost.threshold) {
    weights.shadow += missBoost.shadow;
    weights.chaos += missBoost.chaos;
  }

  if (context.daysRemaining > 0 && context.daysRemaining <= lowDaysBoost.threshold) {
    weights.reward += lowDaysBoost.reward;
  }

  return weights;
};

export const rollEventForHabit = (habit, context = {}) => {
  if (!habit) return null;
  const weights = buildWeights(habit, context);
  const picks = [
    { item: "chaos_quest", weight: weights.chaos },
    { item: "micro_reward", weight: weights.reward },
    { item: "shadow_warning", weight: weights.shadow },
    { item: "pattern_break", weight: weights.pattern },
    { item: "nothing", weight: weights.nothing },
  ];
  const choice = weightedPick(picks);
  if (!choice || choice === "nothing") return null;

  if (choice === "micro_reward") {
    return { type: "micro_reward", reward: weightedReward(), id: uid() };
  }
  if (choice === "chaos_quest") {
    const difficulty = context.streak >= 14 ? "insane" : context.streak >= 7 ? "medium" : "easy";
    return { type: "chaos_quest", quest: makeChaosQuest(difficulty) };
  }
  if (choice === "shadow_warning") {
    return makeShadowWarning(habit);
  }
  if (choice === "pattern_break") {
    return makePatternBreaker();
  }
  return null;
};

export const rollTimeBasedEvent = (date = new Date()) => {
  const minute = date.getMinutes();
  const hour = date.getHours();
  if (minute % 17 === 0) {
    return {
      type: "pattern_break",
      id: uid(),
      title: "Secret 17",
      message: "Take a 17-breath reset and resume.",
    };
  }
  if (hour < 8) {
    return {
      type: "micro_reward",
      reward: { type: "xp", amount: 3, label: "+3 XP" },
      id: uid(),
    };
  }
  if (hour >= 21) {
    return {
      type: "pattern_break",
      id: uid(),
      title: "Night Reflection",
      message: "Log one insight from today before sleep.",
    };
  }
  return null;
};

export default {
  rollEventForHabit,
  rollTimeBasedEvent,
  makeChaosQuest,
  weightedReward,
  weightedPick,
  clamp,
  uid,
};
